apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: IMAGE-TAG # to be replaced
        ports:
        - containerPort: 80
        envFrom:
          - configMapRef:
              name: common-configmap
          - secretRef:
              name: common-secret