apiVersion: kustomize.config.k8s.io/v1alpha1  # <-- Component notation
kind: Component

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: custom-configmap
  literals:
  - FOO=Bar

secretGenerator:
- name: custom-secret
  literals:
  - username=admin
  - password=secret

patchesJson6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: nginx-deployment
  path: deployment.yaml