name: test
on:
  push:

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      -
        name: checkout-app
        uses: actions/checkout@v2
      - 
        name: check if yq exists
        run: |
          yq --help
